### PR TITLE
Security review round one

### PR DESCRIPTION
**Pull request by miohtama**
Hi,

I went through the code with this comb: http://ethereum.stackexchange.com/q/8551/620

Looks solid. I am not worried about token balances themselves. I did not run this through a test suite yet, this was based on core review. To keep up very high standards the following things could be done
- Describe the management of founders key
- Add halt flag to stop buy() in the case you need to stop accepting Ethers for some reason
- Describe and test out founders multisig Ether wallet
- Describe withdrawal process to the founders wallet
- Comment some variables which are not immediately clear from the context

I also outlined "escape hatch" plan if an issue is found with the token code itself.

### CODE REVIEW

**Comment by JasonMcz** [comment]
@zackcoburn 
Add halt flag to stop buy() in the case you need to stop accepting Ethers for some reason. 
I think we should have this functionality just in case.

**Comment by JasonMcz** [comment]
`function transferFrom(address _from, address _to, uint256 _value) returns (bool success) {
        if (block.number <= endBlock + transferLockup && msg.sender!=founder) throw;
        return super.transferFrom(_from, _to, _value);
      }`

Some user asked a question regarding transferLockup calculation. They are wondering what's gonna happen with early termination because of reaching the cap way earlier than 10/24/2016 where the ending_block is intended to be. Are we gonna adjust it or keeping it the same in event of reaching target early.

@miohtama @zackcoburn @anik657

**Comment by miohtama** [comment]
Keep it fixed instead of dynamic by KISS principle.

**Comment by ghost** [comment]
Agreed. Keep it fixed by KISS principle.

I propose that the founder address should be the multisig.

Withdrawing the Ether during the crowdsale has two side effects: 
1. We can't use this.balance to see if we hit the cap. We need to introduce another variable to keep track of the Ether raised. This doesn't seem like an issue, just making a note of it. 
2. People can't just look at the contract on Etherscan and see how much Ether has been raised (people might say, hey, where's all the Ether going!) Is this worth the additional security? Probably. Just throwing this point out there for discussion.

For constantly withdrawing the Ether, we can have the Ether immediately sent to the founder multisig every time someone calls buy(). Then we don't need to keep doing it manually. 

The default function definitely uses more than 2300 gas since it calls the buy() function, but it will throw if it runs out of gas. I expect many people will buy in by sending Ether to the contract directly through the default function, and we're going to have documentation telling them to increase the gas limit if their wallet doesn't do it automatically.

**Comment by ghost** [comment]
I debated how much to include in the constructor parameters versus hardcoding. I think there's something to be said for being able to read the verified source code on Etherscan and see the hardcoded values versus having to verify the constructor inputs. Thoughts?

**Pull request closed without merging**
